// js/products.js
// DỮ LIỆU 60 SẢN PHẨM Shop - ĐÃ CHIA CATEGORY CHUẨN CHO SẢN PHẨM TỪ INDEX.HTML
const products = [
  // === ÁO KHOÁC (1-20 + 51) ===
  { id: 1, name: 'Áo khoác gió 2 lớp mũ tháo rời EWCW001', price: 399000, originalPrice: 600000, discount: 34, category: 'áo khoác', size: ['S', 'M', 'L', 'XL', 'XXL'], color: ['8 Màu'], image: 'images/product1.jpg', previewImages: ['images/preview/product1-1.jpg', 'images/preview/product1-2.jpg', 'images/preview/product1-3.jpg'], description: 'Áo khoác gió 2 lớp mũ tháo rời từ Shop, phong cách bomber.' },
  { id: 2, name: 'Áo khoác gió 2 lớp cổ bomber FWCW005', price: 449000, originalPrice: 650000, discount: 31, category: 'áo khoác', size: ['M', 'L', 'XL'], color: ['7 Màu'], image: 'images/product2.jpg', previewImages: ['images/preview/product2-1.jpg', 'images/preview/product2-2.jpg', 'images/preview/product2-3.jpg'], description: 'Áo khoác gió 2 lớp cổ bomber từ Shop, ấm áp mùa đông.' },
  { id: 3, name: 'Áo khoác da lộn basic cổ cao FWCL002', price: 649000, originalPrice: 850000, discount: 24, category: 'áo khoác', size: ['S', 'M', 'L', 'XL'], color: ['6 Màu'], image: 'images/product3.jpg', previewImages: ['images/preview/product3-1.jpg', 'images/preview/product3-2.jpg'], description: 'Áo khoác da lộn basic cổ cao từ Shop, thời trang đường phố.' },
  { id: 4, name: 'Áo khoác nỉ vải hiệu ứng đáp logo Horse FWCS004', price: 549000, originalPrice: 750000, discount: 27, category: 'áo khoác', size: ['M', 'L', 'XL'], color: ['4 Màu'], image: 'images/product4.jpg', previewImages: ['images/preview/product4-1.jpg', 'images/preview/product4-2.jpg'], description: 'Áo khoác nỉ vải hiệu ứng đáp logo Horse từ Shop.' },
  { id: 11, name: 'Áo khoác gió 1 lớp logo ngực EWCW010', price: 399000, originalPrice: 600000, discount: 34, category: 'áo khoác', size: ['S', 'M', 'L', 'XL'], color: ['2 Màu'], image: 'images/product11.jpg', previewImages: ['images/preview/product11-1.jpg', 'images/preview/product11-2.jpg'], description: 'Áo khoác gió 1 lớp logo ngực từ Shop, đơn giản.' },
  { id: 16, name: 'Áo khoác Puffer cổ cao FWCF004', price: 699000, originalPrice: 990000, discount: 29, category: 'áo khoác', size: ['M', 'L', 'XL'], color: ['5 Màu'], image: 'images/product16.jpg', previewImages: ['images/preview/product16-1.jpg', 'images/preview/product16-2.jpg'], description: 'Áo khoác Puffer cổ cao từ Shop, ấm áp.' },
  { id: 17, name: 'Áo khoác gió 1 lớp mũ liền EWCW007', price: 249000, originalPrice: 500000, discount: 50, category: 'áo khoác', size: ['S', 'M', 'L'], color: ['5 Màu'], image: 'images/product17.jpg', previewImages: ['images/preview/product17-1.jpg', 'images/preview/product17-2.jpg'], description: 'Áo khoác gió 1 lớp mũ liền từ Shop, giá sốc.' },
  { id: 18, name: 'Áo khoác 3 lớp cổ đứng khuy bấm EWCP001', price: 890000, originalPrice: 890000, discount: 0, category: 'áo khoác', size: ['M', 'L', 'XL'], color: ['6 Màu'], image: 'images/product18.jpg', previewImages: ['images/preview/product18-1.jpg', 'images/preview/product18-2.jpg'], description: 'Áo khoác 3 lớp cổ đứng khuy bấm từ Shop, cao cấp.' },
  { id: 19, name: 'Áo khoác gió 2 lớp lót lông cổ cao EWCU001', price: 599000, originalPrice: 750000, discount: 20, category: 'áo khoác', size: ['M', 'L', 'XL'], color: ['7 Màu'], image: 'images/product19.jpg', previewImages: ['images/preview/product19-1.jpg', 'images/preview/product19-2.jpg'], description: 'Áo khoác gió 2 lớp lót lông cổ cao từ Shop.' },
  { id: 20, name: 'Áo khoác gió 2 lớp lót lông cổ cao basic EWCU001', price: 599000, originalPrice: 750000, discount: 20, category: 'áo khoác', size: ['S', 'M', 'L', 'XL'], color: ['7 Màu'], image: 'images/product20.jpg', previewImages: ['images/preview/product20-1.jpg', 'images/preview/product20-2.jpg'], description: 'Áo khoác gió 2 lớp lót lông cổ cao basic từ Shop.' },

  // === ÁO NỈ & PHÔNG (5-14 + 57) ===
  { id: 5, name: 'Áo nỉ bộ trơn basic FWTW024', price: 299000, originalPrice: 420000, discount: 29, category: 'áo nỉ', size: ['S', 'M', 'L'], color: ['4 Màu'], image: 'images/product5.jpg', previewImages: ['images/preview/product5-1.jpg', 'images/preview/product5-2.jpg'], description: 'Áo nỉ bộ trơn basic từ Shop, thoải mái hàng ngày.' },
  { id: 7, name: 'Áo nỉ bộ can phối tay GWTW901', price: 399000, originalPrice: 599000, discount: 33, category: 'áo nỉ', size: ['S', 'M', 'L', 'XL'], color: ['5 Màu'], image: 'images/product7.jpg', previewImages: ['images/preview/product7-1.jpg', 'images/preview/product7-2.jpg'], description: 'Áo nỉ bộ can phối tay từ Shop, GWTW901 - GWBS901.' },
  { id: 57, name: 'Áo Hoodie Nam Xám', price: 550000, originalPrice: 550000, discount: 0, category: 'áo nỉ', size: ['S', 'M', 'L', 'XL'], color: ['4 Màu'], image: 'images/product003.jpg', previewImages: ['images/product003.jpg', 'images/preview/product003-1.jpg', 'images/preview/product003-2.jpg'], description: 'Áo hoodie nam xám thoải mái, phù hợp casual.' },

  // === ÁO POLO (12 + 53) ===
  { id: 12, name: 'Áo polo trơn bo kẻ FSTP003', price: 279000, originalPrice: 420000, discount: 34, category: 'áo polo', size: ['M', 'L', 'XL'], color: ['8 Màu'], image: 'images/product12.jpg', previewImages: ['images/preview/product12-1.jpg', 'images/preview/product12-2.jpg'], description: 'Áo polo trơn bo kẻ từ Shop, thể thao.' },
  { id: 53, name: 'Áo Polo Nam Xanh Dương', price: 450000, originalPrice: 450000, discount: 0, category: 'áo polo', size: ['S', 'M', 'L', 'XL'], color: ['3 Màu'], image: 'images/product03.jpg', previewImages: ['images/product03.jpg', 'images/preview/product03-1.jpg', 'images/preview/product03-2.jpg'], description: 'Áo polo xanh dương thoáng mát, phù hợp văn phòng và dạo phố.' },

  // === ÁO LEN (23, 33, 43 + 54) ===
  { id: 23, name: 'Áo len cổ tròn trơn FWLT001', price: 399000, originalPrice: 550000, discount: 27, category: 'áo len', size: ['S', 'M', 'L'], color: ['5 Màu'], image: 'images/product23.jpg', previewImages: ['images/preview/product23-1.jpg', 'images/preview/product23-2.jpg'], description: 'Áo len cổ tròn trơn từ Shop, ấm áp.' },
  { id: 33, name: 'Áo len cổ lọ FWLT002', price: 449000, originalPrice: 600000, discount: 25, category: 'áo len', size: ['S', 'M', 'L'], color: ['4 Màu'], image: 'images/product33.jpg', previewImages: ['images/preview/product33-1.jpg', 'images/preview/product33-2.jpg'], description: 'Áo len cổ lọ từ Shop.' },
  { id: 43, name: 'Áo len cổ chữ V FWLT003', price: 429000, originalPrice: 590000, discount: 27, category: 'áo len', size: ['S', 'M', 'L'], color: ['4 Màu'], image: 'images/product43.jpg', previewImages: ['images/preview/product43-1.jpg', 'images/preview/product43-2.jpg'], description: 'Áo len cổ chữ V từ Shop.' },
  { id: 54, name: 'Áo Len Nam Dày Dặn', price: 700000, originalPrice: 700000, discount: 0, category: 'áo len', size: ['S', 'M', 'L'], color: ['4 Màu'], image: 'images/product04.jpg', previewImages: ['images/product04.jpg', 'images/preview/product04-1.jpg'], description: 'Áo len dày dặn ấm áp, thiết kế cổ tròn basic từ Shop.' },

  // === ÁO BLAZER (22, 32, 42 + 59) ===
  { id: 22, name: 'Áo blazer basic cổ vuông FWBL001', price: 799000, originalPrice: 999000, discount: 20, category: 'áo blazer', size: ['M', 'L', 'XL'], color: ['4 Màu'], image: 'images/product22.jpg', previewImages: ['images/preview/product22-1.jpg', 'images/preview/product22-2.jpg'], description: 'Áo blazer basic cổ vuông từ Shop.' },
  { id: 32, name: 'Áo blazer kẻ sọc FWBL002', price: 849000, originalPrice: 1050000, discount: 19, category: 'áo blazer', size: ['M', 'L', 'XL'], color: ['3 Màu'], image: 'images/product32.jpg', previewImages: ['images/preview/product32-1.jpg', 'images/preview/product32-2.jpg'], description: 'Áo blazer kẻ sọc từ Shop.' },
  { id: 42, name: 'Áo blazer họa tiết FWBL003', price: 879000, originalPrice: 1100000, discount: 20, category: 'áo blazer', size: ['M', 'L', 'XL'], color: ['3 Màu'], image: 'images/product42.jpg', previewImages: ['images/preview/product42-1.jpg', 'images/preview/product42-2.jpg'], description: 'Áo blazer họa tiết từ Shop.' },
  { id: 59, name: 'Áo Blazer Nam Xanh Navy', price: 1300000, originalPrice: 1300000, discount: 0, category: 'áo blazer', size: ['M', 'L', 'XL'], color: ['3 Màu'], image: 'images/product005.jpg', previewImages: ['images/product005.jpg', 'images/preview/product005-1.jpg'], description: 'Áo blazer xanh navy cổ vuông, phong cách lịch lãm.' },

  // === QUẦN JEANS (15 + 52) ===
  { id: 15, name: 'Quần jeans basic slim EABJ012', price: 399000, originalPrice: 500000, discount: 20, category: 'quần jeans', size: ['28', '30', '32', '34', '36'], color: ['7 Màu'], image: 'images/product15.jpg', previewImages: ['images/preview/product15-1.jpg', 'images/preview/product15-2.jpg'], description: 'Quần jeans basic slim từ Shop, cổ điển.' },
  { id: 52, name: 'Quần Jeans Nam Slim Fit', price: 800000, originalPrice: 800000, discount: 0, category: 'quần jeans', size: ['30', '32', '34', '36'], color: ['5 Màu'], image: 'images/product02.jpg', previewImages: ['images/product02.jpg', 'images/preview/product02-1.jpg', 'images/preview/product02-2.jpg'], description: 'Quần jeans slim fit thoải mái, chất liệu bền bỉ từ Shop.' },

  // === QUẦN DÀI KAKI (24, 34, 44 + 55, 58) ===
  { id: 24, name: 'Quần dài kaki ống suông EWKK001', price: 349000, originalPrice: 450000, discount: 22, category: 'quan dai kaki', size: ['30', '32', '34', '36'], color: ['6 Màu'], image: 'images/product24.jpg', previewImages: ['images/preview/product24-1.jpg', 'images/preview/product24-2.jpg'], description: 'Quần dài kaki ống suông từ Shop.' },
  { id: 34, name: 'Quần dài kaki ống bó EWKK002', price: 379000, originalPrice: 500000, discount: 24, category: 'quan dai kaki', size: ['30', '32', '34', '36'], color: ['5 Màu'], image: 'images/product34.jpg', previewImages: ['images/preview/product34-1.jpg', 'images/preview/product34-2.jpg'], description: 'Quần dài kaki ống bó từ Shop.' },
  { id: 44, name: 'Quần dài kaki ống rộng EWKK003', price: 369000, originalPrice: 490000, discount: 25, category: 'quan dai kaki', size: ['30', '32', '34', '36'], color: ['5 Màu'], image: 'images/product44.jpg', previewImages: ['images/preview/product44-1.jpg', 'images/preview/product44-2.jpg'], description: 'Quần dài kaki ống rộng từ Shop.' },
  { id: 55, name: 'Quần Kaki Nam Đen', price: 650000, originalPrice: 650000, discount: 0, category: 'quan dai kaki', size: ['30', '32', '34'], color: ['2 Màu'], image: 'images/product05.jpg', previewImages: ['images/product05.jpg', 'images/preview/product05-1.jpg', 'images/preview/product05-2.jpg'], description: 'Quần kaki đen ống suông, lịch lãm cho quý ông.' },
  { id: 58, name: 'Quần Jogger Nam Đen', price: 500000, originalPrice: 500000, discount: 0, category: 'quan dai kaki', size: ['M', 'L', 'XL'], color: ['2 Màu'], image: 'images/product004.jpg', previewImages: ['images/product004.jpg', 'images/preview/product004-1.jpg', 'images/preview/product004-2.jpg'], description: 'Quần jogger đen năng động, chất liệu co giãn tốt.' },

  // === PHỤ KIỆN (28-30, 38-40, 48-50 + 56, 60) ===
  { id: 28, name: 'Giày da lười nam GDL001', price: 699000, originalPrice: 850000, discount: 18, category: 'phụ kiện', size: ['39', '40', '41', '42', '43'], color: ['4 Màu'], image: 'images/product28.jpg', previewImages: ['images/preview/product28-1.jpg', 'images/preview/product28-2.jpg'], description: 'Giày da lười nam từ Shop, thời trang.' },
  { id: 29, name: 'Thắt lưng da bò nam TLDB001', price: 499000, originalPrice: 600000, discount: 17, category: 'phụ kiện', size: ['One Size'], color: ['3 Màu'], image: 'images/product29.jpg', previewImages: ['images/preview/product29-1.jpg', 'images/preview/product29-2.jpg'], description: 'Thắt lưng da bò nam từ Shop.' },
  { id: 30, name: 'Túi xách da nam TXD001', price: 899000, originalPrice: 1100000, discount: 18, category: 'phụ kiện', size: ['One Size'], color: ['4 Màu'], image: 'images/product30.jpg', previewImages: ['images/preview/product30-1.jpg', 'images/preview/product30-2.jpg'], description: 'Túi xách da nam từ Shop.' },
  { id: 38, name: 'Giày sneaker nam GSN001', price: 749000, originalPrice: 900000, discount: 17, category: 'phụ kiện', size: ['39', '40', '41', '42', '43'], color: ['5 Màu'], image: 'images/product38.jpg', previewImages: ['images/preview/product38-1.jpg', 'images/preview/product38-2.jpg'], description: 'Giày sneaker nam từ Shop.' },
  { id: 39, name: 'Thắt lưng da lộn TLDN001', price: 429000, originalPrice: 550000, discount: 22, category: 'phụ kiện', size: ['One Size'], color: ['2 Màu'], image: 'images/product39.jpg', previewImages: ['images/preview/product39-1.jpg', 'images/preview/product39-2.jpg'], description: 'Thắt lưng da lộn từ Shop.' },
  { id: 40, name: 'Túi đeo chéo nam TDC001', price: 699000, originalPrice: 850000, discount: 18, category: 'phụ kiện', size: ['One Size'], color: ['3 Màu'], image: 'images/product40.jpg', previewImages: ['images/preview/product40-1.jpg', 'images/preview/product40-2.jpg'], description: 'Túi đeo chéo nam từ Shop.' },
  { id: 48, name: 'Giày boots nam GBT001', price: 899000, originalPrice: 1100000, discount: 18, category: 'phụ kiện', size: ['39', '40', '41', '42', '43'], color: ['3 Màu'], image: 'images/product48.jpg', previewImages: ['images/preview/product48-1.jpg', 'images/preview/product48-2.jpg'], description: 'Giày boots nam từ Shop.' },
  { id: 49, name: 'Thắt lưng vải TLVI001', price: 349000, originalPrice: 450000, discount: 22, category: 'phụ kiện', size: ['One Size'], color: ['2 Màu'], image: 'images/product49.jpg', previewImages: ['images/preview/product49-1.jpg', 'images/preview/product49-2.jpg'], description: 'Thắt lưng vải từ Shop.' },
  { id: 50, name: 'Túi tote nam TTO001', price: 749000, originalPrice: 900000, discount: 17, category: 'phụ kiện', size: ['One Size'], color: ['4 Màu'], image: 'images/product50.jpg', previewImages: ['images/preview/product50-1.jpg', 'images/preview/product50-2.jpg', 'images/preview/product50-3.jpg'], description: 'Túi tote nam từ Shop.' },
  { id: 56, name: 'Giày Da Nam Lịch Lãm', price: 1500000, originalPrice: 1500000, discount: 0, category: 'phụ kiện', size: ['39', '40', '41', '42'], color: ['3 Màu'], image: 'images/product06.jpg', previewImages: ['images/product06.jpg', 'images/preview/product06-1.jpg', 'images/preview/product06-2.jpg'], description: 'Giày da nam lịch lãm, chất liệu cao cấp từ Shop.' },
  { id: 60, name: 'Thắt Lưng Da Nam Đen', price: 400000, originalPrice: 400000, discount: 0, category: 'phụ kiện', size: ['One Size'], color: ['2 Màu'], image: 'images/product006.jpg', previewImages: ['images/product006.jpg', 'images/preview/product006-1.jpg', 'images/preview/product006-2.jpg'], description: 'Thắt lưng da đen nam, thiết kế đơn giản tinh tế.' },

  // === 3 SẢN PHẨM MỚI (DÙNG ẢNH product07 / 08 / 09) ===
  { id: 61, name: 'Combo Áo Khoác + Quần Jeans Mới', price: 1199000, originalPrice: 1599000, discount: 25, category: 'áo khoác', size: ['M', 'L', 'XL'], color: ['3 Màu'], image: 'images/product07.jpg', previewImages: ['images/product07.jpg', 'images/preview/product07-1.jpg', 'images/preview/product07-2.jpg'], description: 'Combo áo khoác + quần jeans cho cuối tuần.' },
  { id: 62, name: 'Blazer + Kaki Công Sở Mới', price: 1790000, originalPrice: 2190000, discount: 18, category: 'áo blazer', size: ['M', 'L', 'XL'], color: ['3 Màu'], image: 'images/product08.jpg', previewImages: ['images/product08.jpg', 'images/preview/product08-1.jpg', 'images/preview/product08-2.jpg'], description: 'Set blazer + quần kaki lịch lãm cho văn phòng.' },
  { id: 63, name: 'Polo + Jeans + Sneaker Mới', price: 1090000, originalPrice: 1390000, discount: 22, category: 'phụ kiện', size: ['39', '40', '41', '42'], color: ['3 Màu'], image: 'images/product09.jpg', previewImages: ['images/product09.jpg', 'images/preview/product09-1.jpg', 'images/preview/product09-2.jpg'], description: 'Combo polo + jeans + sneaker cho cuối tuần năng động.' },

  // === ÁO KHOÁC NAM CAO CẤP (51) ===
  { id: 51, name: 'Áo Khoác Nam Cao Cấp', price: 1200000, originalPrice: 1200000, discount: 0, category: 'áo khoác', size: ['M', 'L', 'XL'], color: ['4 Màu'], image: 'images/product01.jpg', previewImages: ['images/product01.jpg', 'images/preview/product01-1.jpg', 'images/preview/product01-2.jpg'], description: 'Áo khoác nam cao cấp từ Shop, phong cách hiện đại cho mùa đông.' }

  // === CÁC LOẠI KHÁC (quần nỉ, quần âu, quần gió, quần short...) giữ nguyên ===
  // (Không thay đổi vì không có trong index.html)
];
