// <auto-generated />
using System;
using Thuan.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Thuan.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251130094921_InitialSqlServer")]
    partial class InitialSqlServer
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Thuan.API.Models.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("Thuan.API.Models.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("ProductId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("Thuan.API.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShippingAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Thuan.API.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("Thuan.API.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Discount")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("OriginalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PreviewImages")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "áo khoác",
                            Color = "8 Màu",
                            Description = "Áo khoác gió 2 lớp mũ tháo rời từ GUYN, phong cách bomber.",
                            Discount = 34,
                            Image = "images/product1.jpg",
                            Name = "Áo khoác gió 2 lớp mũ tháo rời EWCW001",
                            OriginalPrice = 600000m,
                            PreviewImages = "",
                            Price = 399000m,
                            Size = "S,M,L,XL,XXL",
                            Stock = 100
                        },
                        new
                        {
                            Id = 2,
                            Category = "áo khoác",
                            Color = "7 Màu",
                            Description = "Áo khoác gió 2 lớp cổ bomber từ GUYN, ấm áp mùa đông.",
                            Discount = 31,
                            Image = "images/product2.jpg",
                            Name = "Áo khoác gió 2 lớp cổ bomber FWCW005",
                            OriginalPrice = 650000m,
                            PreviewImages = "",
                            Price = 449000m,
                            Size = "M,L,XL",
                            Stock = 100
                        },
                        new
                        {
                            Id = 3,
                            Category = "áo khoác",
                            Color = "6 Màu",
                            Description = "Áo khoác da lộn basic cổ cao từ GUYN, thời trang đường phố.",
                            Discount = 24,
                            Image = "images/product3.jpg",
                            Name = "Áo khoác da lộn basic cổ cao FWCL002",
                            OriginalPrice = 850000m,
                            PreviewImages = "",
                            Price = 649000m,
                            Size = "S,M,L,XL",
                            Stock = 100
                        },
                        new
                        {
                            Id = 4,
                            Category = "áo khoác",
                            Color = "4 Màu",
                            Description = "Áo khoác nỉ vải hiệu ứng đáp logo Horse từ GUYN.",
                            Discount = 27,
                            Image = "images/product4.jpg",
                            Name = "Áo khoác nỉ vải hiệu ứng đáp logo Horse FWCS004",
                            OriginalPrice = 750000m,
                            PreviewImages = "",
                            Price = 549000m,
                            Size = "M,L,XL",
                            Stock = 100
                        },
                        new
                        {
                            Id = 11,
                            Category = "áo khoác",
                            Color = "2 Màu",
                            Description = "Áo khoác gió 1 lớp logo ngực từ GUYN, đơn giản.",
                            Discount = 34,
                            Image = "images/product11.jpg",
                            Name = "Áo khoác gió 1 lớp logo ngực EWCW010",
                            OriginalPrice = 600000m,
                            PreviewImages = "",
                            Price = 399000m,
                            Size = "S,M,L,XL",
                            Stock = 100
                        },
                        new
                        {
                            Id = 16,
                            Category = "áo khoác",
                            Color = "5 Màu",
                            Description = "Áo khoác Puffer cổ cao từ GUYN, ấm áp.",
                            Discount = 29,
                            Image = "images/product16.jpg",
                            Name = "Áo khoác Puffer cổ cao FWCF004",
                            OriginalPrice = 990000m,
                            PreviewImages = "",
                            Price = 699000m,
                            Size = "M,L,XL",
                            Stock = 100
                        },
                        new
                        {
                            Id = 17,
                            Category = "áo khoác",
                            Color = "5 Màu",
                            Description = "Áo khoác gió 1 lớp mũ liền từ GUYN, giá sốc.",
                            Discount = 50,
                            Image = "images/product17.jpg",
                            Name = "Áo khoác gió 1 lớp mũ liền EWCW007",
                            OriginalPrice = 500000m,
                            PreviewImages = "",
                            Price = 249000m,
                            Size = "S,M,L",
                            Stock = 100
                        },
                        new
                        {
                            Id = 18,
                            Category = "áo khoác",
                            Color = "6 Màu",
                            Description = "Áo khoác 3 lớp cổ đứng khuy bấm từ GUYN, cao cấp.",
                            Discount = 0,
                            Image = "images/product18.jpg",
                            Name = "Áo khoác 3 lớp cổ đứng khuy bấm EWCP001",
                            OriginalPrice = 890000m,
                            PreviewImages = "",
                            Price = 890000m,
                            Size = "M,L,XL",
                            Stock = 100
                        },
                        new
                        {
                            Id = 19,
                            Category = "áo khoác",
                            Color = "7 Màu",
                            Description = "Áo khoác gió 2 lớp lót lông cổ cao từ GUYN.",
                            Discount = 20,
                            Image = "images/product19.jpg",
                            Name = "Áo khoác gió 2 lớp lót lông cổ cao EWCU001",
                            OriginalPrice = 750000m,
                            PreviewImages = "",
                            Price = 599000m,
                            Size = "M,L,XL",
                            Stock = 100
                        },
                        new
                        {
                            Id = 20,
                            Category = "áo khoác",
                            Color = "7 Màu",
                            Description = "Áo khoác gió 2 lớp lót lông cổ cao basic từ GUYN.",
                            Discount = 20,
                            Image = "images/product20.jpg",
                            Name = "Áo khoác gió 2 lớp lót lông cổ cao basic EWCU001",
                            OriginalPrice = 750000m,
                            PreviewImages = "",
                            Price = 599000m,
                            Size = "S,M,L,XL",
                            Stock = 100
                        },
                        new
                        {
                            Id = 51,
                            Category = "áo khoác",
                            Color = "4 Màu",
                            Description = "Áo khoác nam cao cấp từ GUYN, phong cách hiện đại cho mùa đông.",
                            Discount = 0,
                            Image = "images/product01.jpg",
                            Name = "Áo Khoác Nam Cao Cấp",
                            OriginalPrice = 1200000m,
                            PreviewImages = "",
                            Price = 1200000m,
                            Size = "M,L,XL",
                            Stock = 100
                        },
                        new
                        {
                            Id = 5,
                            Category = "áo nỉ",
                            Color = "4 Màu",
                            Description = "Áo nỉ bộ trơn basic từ GUYN, thoải mái hàng ngày.",
                            Discount = 29,
                            Image = "images/product5.jpg",
                            Name = "Áo nỉ bộ trơn basic FWTW024",
                            OriginalPrice = 420000m,
                            PreviewImages = "",
                            Price = 299000m,
                            Size = "S,M,L",
                            Stock = 100
                        },
                        new
                        {
                            Id = 7,
                            Category = "áo nỉ",
                            Color = "5 Màu",
                            Description = "Áo nỉ bộ can phối tay từ GUYN, GWTW901 - GWBS901.",
                            Discount = 33,
                            Image = "images/product7.jpg",
                            Name = "Áo nỉ bộ can phối tay GWTW901",
                            OriginalPrice = 599000m,
                            PreviewImages = "",
                            Price = 399000m,
                            Size = "S,M,L,XL",
                            Stock = 100
                        },
                        new
                        {
                            Id = 57,
                            Category = "áo nỉ",
                            Color = "4 Màu",
                            Description = "Áo hoodie nam xám thoải mái, phù hợp casual.",
                            Discount = 0,
                            Image = "images/product003.jpg",
                            Name = "Áo Hoodie Nam Xám",
                            OriginalPrice = 550000m,
                            PreviewImages = "",
                            Price = 550000m,
                            Size = "S,M,L,XL",
                            Stock = 100
                        },
                        new
                        {
                            Id = 12,
                            Category = "áo polo",
                            Color = "8 Màu",
                            Description = "Áo polo trơn bo kẻ từ GUYN, thể thao.",
                            Discount = 34,
                            Image = "images/product12.jpg",
                            Name = "Áo polo trơn bo kẻ FSTP003",
                            OriginalPrice = 420000m,
                            PreviewImages = "",
                            Price = 279000m,
                            Size = "M,L,XL",
                            Stock = 100
                        },
                        new
                        {
                            Id = 53,
                            Category = "áo polo",
                            Color = "3 Màu",
                            Description = "Áo polo xanh dương thoáng mát, phù hợp văn phòng và dạo phố.",
                            Discount = 0,
                            Image = "images/product03.jpg",
                            Name = "Áo Polo Nam Xanh Dương",
                            OriginalPrice = 450000m,
                            PreviewImages = "",
                            Price = 450000m,
                            Size = "S,M,L,XL",
                            Stock = 100
                        },
                        new
                        {
                            Id = 23,
                            Category = "áo len",
                            Color = "5 Màu",
                            Description = "Áo len cổ tròn trơn từ GUYN, ấm áp.",
                            Discount = 27,
                            Image = "images/product23.jpg",
                            Name = "Áo len cổ tròn trơn FWLT001",
                            OriginalPrice = 550000m,
                            PreviewImages = "",
                            Price = 399000m,
                            Size = "S,M,L",
                            Stock = 100
                        },
                        new
                        {
                            Id = 33,
                            Category = "áo len",
                            Color = "4 Màu",
                            Description = "Áo len cổ lọ từ GUYN.",
                            Discount = 25,
                            Image = "images/product33.jpg",
                            Name = "Áo len cổ lọ FWLT002",
                            OriginalPrice = 600000m,
                            PreviewImages = "",
                            Price = 449000m,
                            Size = "S,M,L",
                            Stock = 100
                        },
                        new
                        {
                            Id = 43,
                            Category = "áo len",
                            Color = "4 Màu",
                            Description = "Áo len cổ chữ V từ GUYN.",
                            Discount = 27,
                            Image = "images/product43.jpg",
                            Name = "Áo len cổ chữ V FWLT003",
                            OriginalPrice = 590000m,
                            PreviewImages = "",
                            Price = 429000m,
                            Size = "S,M,L",
                            Stock = 100
                        },
                        new
                        {
                            Id = 54,
                            Category = "áo len",
                            Color = "4 Màu",
                            Description = "Áo len dày dặn ấm áp, thiết kế cổ tròn basic từ GUYN.",
                            Discount = 0,
                            Image = "images/product04.jpg",
                            Name = "Áo Len Nam Dày Dặn",
                            OriginalPrice = 700000m,
                            PreviewImages = "",
                            Price = 700000m,
                            Size = "S,M,L",
                            Stock = 100
                        },
                        new
                        {
                            Id = 22,
                            Category = "áo blazer",
                            Color = "4 Màu",
                            Description = "Áo blazer basic cổ vuông từ GUYN.",
                            Discount = 20,
                            Image = "images/product22.jpg",
                            Name = "Áo blazer basic cổ vuông FWBL001",
                            OriginalPrice = 999000m,
                            PreviewImages = "",
                            Price = 799000m,
                            Size = "M,L,XL",
                            Stock = 100
                        },
                        new
                        {
                            Id = 32,
                            Category = "áo blazer",
                            Color = "3 Màu",
                            Description = "Áo blazer kẻ sọc từ GUYN.",
                            Discount = 19,
                            Image = "images/product32.jpg",
                            Name = "Áo blazer kẻ sọc FWBL002",
                            OriginalPrice = 1050000m,
                            PreviewImages = "",
                            Price = 849000m,
                            Size = "M,L,XL",
                            Stock = 100
                        },
                        new
                        {
                            Id = 42,
                            Category = "áo blazer",
                            Color = "3 Màu",
                            Description = "Áo blazer họa tiết từ GUYN.",
                            Discount = 20,
                            Image = "images/product42.jpg",
                            Name = "Áo blazer họa tiết FWBL003",
                            OriginalPrice = 1100000m,
                            PreviewImages = "",
                            Price = 879000m,
                            Size = "M,L,XL",
                            Stock = 100
                        },
                        new
                        {
                            Id = 59,
                            Category = "áo blazer",
                            Color = "3 Màu",
                            Description = "Áo blazer xanh navy cổ vuông, phong cách lịch lãm.",
                            Discount = 0,
                            Image = "images/product005.jpg",
                            Name = "Áo Blazer Nam Xanh Navy",
                            OriginalPrice = 1300000m,
                            PreviewImages = "",
                            Price = 1300000m,
                            Size = "M,L,XL",
                            Stock = 100
                        },
                        new
                        {
                            Id = 15,
                            Category = "quần jeans",
                            Color = "7 Màu",
                            Description = "Quần jeans basic slim từ GUYN, cổ điển.",
                            Discount = 20,
                            Image = "images/product15.jpg",
                            Name = "Quần jeans basic slim EABJ012",
                            OriginalPrice = 500000m,
                            PreviewImages = "",
                            Price = 399000m,
                            Size = "28,30,32,34,36",
                            Stock = 100
                        },
                        new
                        {
                            Id = 52,
                            Category = "quần jeans",
                            Color = "5 Màu",
                            Description = "Quần jeans slim fit thoải mái, chất liệu bền bỉ từ GUYN.",
                            Discount = 0,
                            Image = "images/product02.jpg",
                            Name = "Quần Jeans Nam Slim Fit",
                            OriginalPrice = 800000m,
                            PreviewImages = "",
                            Price = 800000m,
                            Size = "30,32,34,36",
                            Stock = 100
                        },
                        new
                        {
                            Id = 24,
                            Category = "quan dai kaki",
                            Color = "6 Màu",
                            Description = "Quần dài kaki ống suông từ GUYN.",
                            Discount = 22,
                            Image = "images/product24.jpg",
                            Name = "Quần dài kaki ống suông EWKK001",
                            OriginalPrice = 450000m,
                            PreviewImages = "",
                            Price = 349000m,
                            Size = "30,32,34,36",
                            Stock = 100
                        },
                        new
                        {
                            Id = 34,
                            Category = "quan dai kaki",
                            Color = "5 Màu",
                            Description = "Quần dài kaki ống bó từ GUYN.",
                            Discount = 24,
                            Image = "images/product34.jpg",
                            Name = "Quần dài kaki ống bó EWKK002",
                            OriginalPrice = 500000m,
                            PreviewImages = "",
                            Price = 379000m,
                            Size = "30,32,34,36",
                            Stock = 100
                        },
                        new
                        {
                            Id = 44,
                            Category = "quan dai kaki",
                            Color = "5 Màu",
                            Description = "Quần dài kaki ống rộng từ GUYN.",
                            Discount = 25,
                            Image = "images/product44.jpg",
                            Name = "Quần dài kaki ống rộng EWKK003",
                            OriginalPrice = 490000m,
                            PreviewImages = "",
                            Price = 369000m,
                            Size = "30,32,34,36",
                            Stock = 100
                        },
                        new
                        {
                            Id = 55,
                            Category = "quan dai kaki",
                            Color = "2 Màu",
                            Description = "Quần kaki đen ống suông, lịch lãm cho quý ông.",
                            Discount = 0,
                            Image = "images/product05.jpg",
                            Name = "Quần Kaki Nam Đen",
                            OriginalPrice = 650000m,
                            PreviewImages = "",
                            Price = 650000m,
                            Size = "30,32,34",
                            Stock = 100
                        },
                        new
                        {
                            Id = 58,
                            Category = "quan dai kaki",
                            Color = "2 Màu",
                            Description = "Quần jogger đen năng động, chất liệu co giãn tốt.",
                            Discount = 0,
                            Image = "images/product004.jpg",
                            Name = "Quần Jogger Nam Đen",
                            OriginalPrice = 500000m,
                            PreviewImages = "",
                            Price = 500000m,
                            Size = "M,L,XL",
                            Stock = 100
                        },
                        new
                        {
                            Id = 28,
                            Category = "phụ kiện",
                            Color = "4 Màu",
                            Description = "Giày da lười nam từ GUYN, thời trang.",
                            Discount = 18,
                            Image = "images/product28.jpg",
                            Name = "Giày da lười nam GDL001",
                            OriginalPrice = 850000m,
                            PreviewImages = "",
                            Price = 699000m,
                            Size = "39,40,41,42,43",
                            Stock = 100
                        },
                        new
                        {
                            Id = 29,
                            Category = "phụ kiện",
                            Color = "3 Màu",
                            Description = "Thắt lưng da bò nam từ GUYN.",
                            Discount = 17,
                            Image = "images/product29.jpg",
                            Name = "Thắt lưng da bò nam TLDB001",
                            OriginalPrice = 600000m,
                            PreviewImages = "",
                            Price = 499000m,
                            Size = "One Size",
                            Stock = 100
                        },
                        new
                        {
                            Id = 30,
                            Category = "phụ kiện",
                            Color = "4 Màu",
                            Description = "Túi xách da nam từ GUYN.",
                            Discount = 18,
                            Image = "images/product30.jpg",
                            Name = "Túi xách da nam TXD001",
                            OriginalPrice = 1100000m,
                            PreviewImages = "",
                            Price = 899000m,
                            Size = "One Size",
                            Stock = 100
                        },
                        new
                        {
                            Id = 38,
                            Category = "phụ kiện",
                            Color = "5 Màu",
                            Description = "Giày sneaker nam từ GUYN.",
                            Discount = 17,
                            Image = "images/product38.jpg",
                            Name = "Giày sneaker nam GSN001",
                            OriginalPrice = 900000m,
                            PreviewImages = "",
                            Price = 749000m,
                            Size = "39,40,41,42,43",
                            Stock = 100
                        },
                        new
                        {
                            Id = 39,
                            Category = "phụ kiện",
                            Color = "2 Màu",
                            Description = "Thắt lưng da lộn từ GUYN.",
                            Discount = 22,
                            Image = "images/product39.jpg",
                            Name = "Thắt lưng da lộn TLDN001",
                            OriginalPrice = 550000m,
                            PreviewImages = "",
                            Price = 429000m,
                            Size = "One Size",
                            Stock = 100
                        },
                        new
                        {
                            Id = 40,
                            Category = "phụ kiện",
                            Color = "3 Màu",
                            Description = "Túi đeo chéo nam từ GUYN.",
                            Discount = 18,
                            Image = "images/product40.jpg",
                            Name = "Túi đeo chéo nam TDC001",
                            OriginalPrice = 850000m,
                            PreviewImages = "",
                            Price = 699000m,
                            Size = "One Size",
                            Stock = 100
                        },
                        new
                        {
                            Id = 48,
                            Category = "phụ kiện",
                            Color = "3 Màu",
                            Description = "Giày boots nam từ GUYN.",
                            Discount = 18,
                            Image = "images/product48.jpg",
                            Name = "Giày boots nam GBT001",
                            OriginalPrice = 1100000m,
                            PreviewImages = "",
                            Price = 899000m,
                            Size = "39,40,41,42,43",
                            Stock = 100
                        },
                        new
                        {
                            Id = 49,
                            Category = "phụ kiện",
                            Color = "2 Màu",
                            Description = "Thắt lưng vải từ GUYN.",
                            Discount = 22,
                            Image = "images/product49.jpg",
                            Name = "Thắt lưng vải TLVI001",
                            OriginalPrice = 450000m,
                            PreviewImages = "",
                            Price = 349000m,
                            Size = "One Size",
                            Stock = 100
                        },
                        new
                        {
                            Id = 50,
                            Category = "phụ kiện",
                            Color = "4 Màu",
                            Description = "Túi tote nam từ GUYN.",
                            Discount = 17,
                            Image = "images/product50.jpg",
                            Name = "Túi tote nam TTO001",
                            OriginalPrice = 900000m,
                            PreviewImages = "",
                            Price = 749000m,
                            Size = "One Size",
                            Stock = 100
                        },
                        new
                        {
                            Id = 56,
                            Category = "phụ kiện",
                            Color = "3 Màu",
                            Description = "Giày da nam lịch lãm, chất liệu cao cấp từ GUYN.",
                            Discount = 0,
                            Image = "images/product06.jpg",
                            Name = "Giày Da Nam Lịch Lãm",
                            OriginalPrice = 1500000m,
                            PreviewImages = "",
                            Price = 1500000m,
                            Size = "39,40,41,42",
                            Stock = 100
                        },
                        new
                        {
                            Id = 60,
                            Category = "phụ kiện",
                            Color = "2 Màu",
                            Description = "Thắt lưng da đen nam, thiết kế đơn giản tinh tế.",
                            Discount = 0,
                            Image = "images/product006.jpg",
                            Name = "Thắt Lưng Da Nam Đen",
                            OriginalPrice = 400000m,
                            PreviewImages = "",
                            Price = 400000m,
                            Size = "One Size",
                            Stock = 100
                        });
                });

            modelBuilder.Entity("Thuan.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Thuan.API.Models.Cart", b =>
                {
                    b.HasOne("Thuan.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Thuan.API.Models.CartItem", b =>
                {
                    b.HasOne("Thuan.API.Models.Cart", "Cart")
                        .WithMany("Items")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Thuan.API.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Thuan.API.Models.Order", b =>
                {
                    b.HasOne("Thuan.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Thuan.API.Models.OrderItem", b =>
                {
                    b.HasOne("Thuan.API.Models.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Thuan.API.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Thuan.API.Models.Cart", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Thuan.API.Models.Order", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
